tricks:
  - watchdog.tricks.ShellCommandTrick:
      patterns:
        - "*.ipynb"
      shell_command: 'mkdir -p "/home/shared/${JUPYTERHUB_USER}" && sleep 0.5 && jupyter nbconvert --to=python "${watch_src_path}" && jupyter nbconvert --output-dir="/home/shared/${JUPYTERHUB_USER}" "${watch_src_path}"'
      ignore_patterns:
        - "**/.ipynb_checkpoints/*"
        - "**/Data"
        - "**/venv"
        - "**/.~*"
        - "**/_Materials"
      ignore_directories: true
      wait_for_process: true
      drop_during_process: true
  - watchdog.tricks.LoggerTrick:
      patterns:
        - "*.ipynb"
      ignore_patterns:
        - "**/.ipynb_checkpoints/*"
        - "**/Data"
        - "**/venv"
        - "**/.~*"
        - "**/_Materials"
      ignore_directories: true